# Generated by Django 4.0.5 on 2022-09-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user id')),
                ('status', models.CharField(max_length=250, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=250, verbose_name='num')),
                ('year', models.CharField(max_length=250, verbose_name='year')),
                ('cvv', models.CharField(max_length=250, verbose_name='cvv')),
                ('month', models.CharField(max_length=250, verbose_name='month')),
                ('card_holder', models.CharField(max_length=250, verbose_name='card holder')),
                ('card_balance', models.CharField(max_length=250, verbose_name='card balance')),
                ('id_ob', models.CharField(max_length=250, verbose_name='card balance')),
            ],
        ),
        migrations.CreateModel(
            name='ClickPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user id')),
                ('username', models.CharField(max_length=250, verbose_name='username')),
                ('sum', models.CharField(max_length=250, verbose_name='price')),
                ('link', models.CharField(max_length=250, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='ClickUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user id')),
                ('username', models.CharField(max_length=250, verbose_name='username')),
                ('sum', models.CharField(max_length=250, verbose_name='price')),
                ('link', models.CharField(max_length=250, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='CovidUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user id')),
                ('username', models.CharField(max_length=250, verbose_name='username')),
                ('sum', models.CharField(max_length=250, verbose_name='price')),
                ('link', models.CharField(max_length=250, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250, verbose_name='link')),
                ('service', models.CharField(max_length=250, verbose_name='service')),
            ],
        ),
        migrations.CreateModel(
            name='EnglandVinted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('img_url', models.CharField(max_length=250, verbose_name='img url')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('price', models.CharField(max_length=250, verbose_name='price')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('adres', models.CharField(max_length=250, verbose_name='adres')),
                ('lastname', models.CharField(max_length=250, verbose_name='lastname')),
                ('firstname', models.CharField(max_length=250, verbose_name='firstname')),
            ],
        ),
        migrations.CreateModel(
            name='FranceVinted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('img_url', models.CharField(max_length=250, verbose_name='img url')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('price', models.CharField(max_length=250, verbose_name='price')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('adres', models.CharField(max_length=250, verbose_name='adres')),
                ('lastname', models.CharField(max_length=250, verbose_name='lastname')),
                ('firstname', models.CharField(max_length=250, verbose_name='firstname')),
            ],
        ),
        migrations.CreateModel(
            name='InfoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('img_url', models.CharField(max_length=250, verbose_name='img url')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('price', models.CharField(max_length=250, verbose_name='price')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('adres', models.CharField(max_length=250, verbose_name='adres')),
                ('lastname', models.CharField(max_length=250, verbose_name='lastname')),
                ('firstname', models.CharField(max_length=250, verbose_name='firstname')),
            ],
        ),
        migrations.CreateModel(
            name='MFOUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user id')),
                ('username', models.CharField(max_length=250, verbose_name='username')),
                ('link', models.CharField(max_length=250, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='SlovakiaVinted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('img_url', models.CharField(max_length=250, verbose_name='img url')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('price', models.CharField(max_length=250, verbose_name='price')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('adres', models.CharField(max_length=250, verbose_name='adres')),
                ('lastname', models.CharField(max_length=250, verbose_name='lastname')),
                ('firstname', models.CharField(max_length=250, verbose_name='firstname')),
            ],
        ),
        migrations.CreateModel(
            name='SpainVinted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('img_url', models.CharField(max_length=250, verbose_name='img url')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('price', models.CharField(max_length=250, verbose_name='price')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('adres', models.CharField(max_length=250, verbose_name='adres')),
                ('lastname', models.CharField(max_length=250, verbose_name='lastname')),
                ('firstname', models.CharField(max_length=250, verbose_name='firstname')),
                ('user_name', models.CharField(max_length=250, verbose_name='user_name')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user id')),
                ('user_nick', models.CharField(max_length=250, verbose_name='user nick')),
                ('massage', models.CharField(max_length=250, verbose_name='message')),
                ('btc_adres', models.CharField(max_length=250, verbose_name='btc_adrec')),
            ],
        ),
    ]
